# Generated by Django 5.2 on 2025-08-26 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attandenceDashBoard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeregistration',
            name='cAddress',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employeeregistration',
            name='cState',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employeeregistration',
            name='ccity',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employeeregistration',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employeeregistration',
            name='oEmployerName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employeeregistration',
            name='pAddress',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='employeeregistration',
            name='pState',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employeeregistration',
            name='pcity',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employeeregistration',
            name='refrerName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employeeregistration',
            name='sonOf',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Failedattandence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=None)),
                ('singInTimeA', models.TimeField(default=None, null=True)),
                ('siginImageA', models.ImageField(default=None, upload_to='static/signinFailed/')),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attandenceDashBoard.employeeregistration')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=None)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attandenceDashBoard.employeeregistration')),
            ],
        ),
    ]
