# Generated by Django 5.2 on 2025-08-29 07:19

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attandenceDashBoard', '0002_alter_employeeregistration_caddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='allowedHalfDay',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='department',
            name='allowedLeave',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='department',
            name='earlyRelifeMinutes',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='department',
            name='intime',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
        migrations.AddField(
            model_name='department',
            name='outTIme',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AddField(
            model_name='department',
            name='workingHour',
            field=models.IntegerField(default=8),
        ),
        migrations.CreateModel(
            name='SalaryOfEveryPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salaryPerMonth', models.FloatField(default=0)),
                ('emp', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='attandenceDashBoard.employeeregistration')),
            ],
        ),
    ]
