# Generated by Django 5.2 on 2025-08-29 07:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attandenceDashBoard', '0003_department_allowedhalfday_department_allowedleave_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='employeeEveryMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthDate', models.DateField(default=datetime.date(2025, 8, 1))),
                ('employee', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='attandenceDashBoard.employeeregistration')),
            ],
        ),
    ]
