# Generated by Django 5.2 on 2025-08-29 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attandenceDashBoard', '0004_employeeeverymonth'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeeverymonth',
            name='absentDueTolate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='employeeeverymonth',
            name='allowedLeaveTaken',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeeeverymonth',
            name='earlyOut',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeeeverymonth',
            name='halfDay',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeeeverymonth',
            name='late',
            field=models.IntegerField(default=0),
        ),
    ]
