# Generated by Django 5.2 on 2025-08-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attandenceDashBoard', '0005_employeeeverymonth_absentduetolate_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='employeeEveryMonth',
            new_name='employeeRecordEveryMonth',
        ),
        migrations.RenameField(
            model_name='employeerecordeverymonth',
            old_name='allowedLeaveTaken',
            new_name='allowedLeaveTakens',
        ),
        migrations.RenameField(
            model_name='employeerecordeverymonth',
            old_name='earlyOut',
            new_name='earlyOuts',
        ),
        migrations.RenameField(
            model_name='employeerecordeverymonth',
            old_name='halfDay',
            new_name='halfDays',
        ),
        migrations.RenameField(
            model_name='employeerecordeverymonth',
            old_name='late',
            new_name='lateDays',
        ),
        migrations.AddField(
            model_name='department',
            name='earlyRelifeDays',
            field=models.IntegerField(default=2),
        ),
    ]
