# Generated by Django 5.2 on 2025-09-01 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attandenceDashBoard', '0006_rename_employeeeverymonth_employeerecordeverymonth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeerecordeverymonth',
            name='monthDate',
            field=models.DateField(default=datetime.date(2025, 9, 1)),
        ),
    ]
