# Generated by Django 5.2 on 2025-09-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attandenceDashBoard', '0007_alter_employeerecordeverymonth_monthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='lateDaysCount',
            field=models.IntegerField(default=0),
        ),
    ]
