# Generated by Django 5.2 on 2025-09-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attandenceDashBoard', '0008_department_latedayscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='lateDaysCount',
            field=models.IntegerField(default=2),
        ),
    ]
