# Generated by Django 5.2 on 2025-09-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attandenceDashBoard', '0009_alter_department_latedayscount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='earlyRelifeMinutes',
            new_name='earlyRelifeHour',
        ),
        migrations.AddField(
            model_name='employeerecordeverymonth',
            name='halfDaysDuetolate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employeerecordeverymonth',
            name='allowedLeaveTakens',
            field=models.IntegerField(default=2),
        ),
    ]
