# Generated by Django 5.2 on 2025-09-04 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attandenceDashBoard', '0010_rename_earlyrelifeminutes_department_earlyrelifehour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeerecordeverymonth',
            name='allowedLeaveTakens',
            field=models.IntegerField(default=0),
        ),
    ]
