# Generated by Django 5.2 on 2025-09-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attandenceDashBoard', '0011_alter_employeerecordeverymonth_allowedleavetakens'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerecordeverymonth',
            name='absents',
            field=models.IntegerField(default=0),
        ),
    ]
