# Generated by Django 5.2 on 2025-09-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attandenceDashBoard', '0012_employeerecordeverymonth_absents'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerecordeverymonth',
            name='totalsalary',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='employeerecordeverymonth',
            name='totalunpaidDays',
            field=models.FloatField(default=0.0),
        ),
    ]
