# Generated by Django 5.2 on 2025-09-05 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attandenceDashBoard', '0013_employeerecordeverymonth_totalsalary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryofeveryperson',
            name='emp',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='attandenceDashBoard.employeeregistration', unique=True),
        ),
    ]
