# Generated by Django 5.2 on 2025-12-17 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attandenceDashBoard', '0014_alter_salaryofeveryperson_emp'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeregistration',
            name='shift',
            field=models.CharField(blank=True, choices=[('DAY', 'Day'), ('NIGHT', 'Night')], default='Day', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='employeerecordeverymonth',
            name='monthDate',
            field=models.DateField(default=datetime.date(2025, 12, 1)),
        ),
    ]
