# Generated by Django 5.2 on 2025-12-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attandenceDashBoard', '0015_employeeregistration_shift_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeregistration',
            name='emplyooetype',
            field=models.CharField(blank=True, choices=[('MONTHLY', 'Monthly'), ('WEEKLY', 'Weekly')], default='Monthly', max_length=7, null=True),
        ),
    ]
