# Generated by Django 5.2 on 2025-12-25 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attandenceDashBoard', '0016_employeeregistration_emplyooetype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeregistration',
            old_name='emplyooetype',
            new_name='employeetype',
        ),
    ]
