# Generated by Django 5.2 on 2025-12-25 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attandenceDashBoard', '0017_rename_emplyooetype_employeeregistration_employeetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyHolidays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holidayPerMonth', models.IntegerField(default=0)),
                ('monthName', models.DateField(default=datetime.date(2025, 12, 1))),
            ],
        ),
    ]
